package.json

Changed name of project in package.json

---

package-lock.json
package.json
src/App.css
src/App.js
src/components/routeList/RouteCard.js
src/components/routeList/RouteCard.test.js
src/components/routeList/RouteCardLayout.css
src/components/routeList/RouteCardStyle.css
src/components/routeList/RouteList.js
src/components/routeList/RouteList.test.js
src/index.js

Prototype of route card display. Components and css.

Feature route list gui

---

src/App.js
src/components/myMap/MyMap.js
src/components/myMap/MyMap.test.js
src/components/myMap/Route.js
src/components/routeList/RouteCard.js
src/components/routeList/RouteList.js

- Modified route cards so they show a map on their header position with
a set of points received inside props object.
- Added missing semicolons on some files so that codacy doesn't
complain.
- Formatted some files.
Close #38

Several modifications. Read commit description.

---

src/components/podService/storageHandler.js
src/pages/MapCreation.js

Fixes #46 as routes are read and transformed as a JSON from the pod (the class StorageHandler takes care of this)

Feature get routes from pod

---

src/tests/App.test.js
src/tests/MapCreation.test.js
src/tests/MyMap.test.js
src/tests/RouteCard.test.js
src/tests/RouteList.test.js

Moved tests to a separate folder as decided in today's meeting.
Closes #63

Fixed App.test and moved tests to a separate folder inside src

---

src/docs/04_solution_strategy.adoc
src/docs/12_glossary.adoc

Following teacher's advices, this docs part is now more concise.
And it features a table with some quality goals. As stated on the ARC42
documentation recomendations.
Closes #96

Rewrote part 4 of the documentation

---

src/components/navBar/navBar.jsx
src/components/podService/podStoreHandler.js
src/components/podService/solid_file_client.js
src/model/MyRoute.js
src/model/RouteManager.js
src/model/RouteWaypoint.js
src/pages/InfoView.js
src/pages/MapCreation.js
src/pages/Profile.js
src/tests/InfoView.test.js

New route POD upload complete

---

src/components/podService/podStoreHandler.js

Fixes #106 
Now folders will be automatically created when nor present.
Added a deleteAll method which completely removes all data regarding viade from the pod.

Fix issue106

---

src/components/routeList/RouteList.js
src/model/RouteManager.js

Modified route RouteManager.
Closes #113

Async component created on route list

---

src/pages/InfoView.js

Now the route info view reloads the page and if needed it fetches the route from the POD to show it to the user.
Closes #108

Now the page reloads without crashing thanks to the state modification

---

src/docs/02_architecture_constraints.adoc

Updated documentation part 2, deleting extra contents not needed in this part

Documentation revisited 02

---

src/pages/ShareView.js

Fixed name of the notification

---

src/components/navBar/navBar.js
src/components/navBar/navBarNotAuthenticated.js
src/pages/Home.js

Little changes  in styles and version of the app

Fix typos and style

---

src/components/podService/podStoreHandler.js
src/model/MyRoute.js
src/model/RouteMedia.js
src/pages/InfoView.js
src/pages/MapCreation.js

Fixes #88, #156 
Pictures can be uploaded to the pod and when a route does have media, it is displayed on the Info View.
The media is represented by a new Class called "RouteMedia" (The routes contain an array of these of object type)

Upload media and display on Route Info View

---

package.json
src/components/editableMap/EditableMap.js
src/components/routeList/RouteList.js
src/i18n.js
src/pages/MapCreation.js
src/tests/MapCreation.test.js

I have changed the ugly navigator alerts by "react-toastify" library alerts. What do you think about them? Any idea on how to internationalize them? I also added loading icons while downloading and uploading routes.

Better alerts in route creation

---

README.md

Added links in the readme index to all the sections. 
Created how-to-use guide. Any more suggestions in things to include there? 
@Drastur maybe you want to include something about Docker.

Feature new readme

---

src/components/navBar/navBar.js
src/components/podService/podStoreHandler.js
src/components/routeCreation/SearchBar.js
src/components/routeList/RouteCard.js
src/model/MyRoute.js
src/model/RouteManager.js
src/model/RoutePoint.js
src/pages/InfoView.js
src/pages/RouteCreation.js
src/pages/RouteList.js
src/tests/InfoView.test.js
src/tests/MapCreation.test.js
src/tests/RouteList.test.js
src/tests/RouteManager.test.js

In previous version, creating a route wouldn't calculate elevations until the very last moment before uploading it to the POD. 
Now it does every single time the map is modified asynchronously. It works although we'd probably need to check whether or not there are points without altitude when trying to upload it. and so warn the user with a toast. 
I mean, right before uploading it -the user clicks "upload to pod"-, we check if some point is waiting for its altitude with some boolean value in their class -RoutePoint-. This way we improve usability and data consistency inside the POD.

Several modifications. Read description

---

src/components/navBar/navBar.js
src/components/podService/podPermissionHandler.js
src/components/podService/podStoreHandler.js
src/components/routeCreation/SearchBar.js
src/i18n.js
src/model/Util.js
src/pages/Groups.js
src/pages/Home.js
src/pages/InfoView.js
src/pages/Profile.js
src/pages/RouteHelp.js
src/pages/RouteList.js
src/pages/RouteSharedList.js
src/pages/ShareView.js
src/pages/createGroup.js

After some work @jesQM and I have figured out how to handle the errors when some shared routes are not shown.
Now, you will get one unique alert indicating this problem, and we have provided also a way to delete all routes shared to you, which makes the alert to not show up again. 
In addition, all alerts have been internationalized. #200

Fix handle incorrect permissions & Alert internationalization

---

src/model/Util.js
src/pages/Profile.js

Profile not broken the app when no solid pod info stored

profile fixed

---

src/components/routeCreation/RouteCreationForm.js
src/pages/Profile.js
src/pages/RouteCreation.js
src/pages/RouteList.js
src/pages/RouteSharedList.js

Clean project warnings

---

src/components/pointInfo/PointInfo.js
src/components/routeCreation/RouteCreationForm.js
src/components/routeCreation/SearchBar.js
src/components/routeList/RouteCard.js
src/i18n.js
src/pages/InfoView.js
src/pages/ShareView.js

I18n last issues
